# -*- coding: utf-8 -*-
"""0-python-basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Br-mvkwaH7TRzWtWrhhC9ZAyx-LZDZfP

# 0. Hello, Python! (Basic Data Types)

This is a Python refresher notebook. It covers the basic data types in Python.
"""

# --- Numeric Types ---
# Integer


# Float


# Complex


# --- String and Character ---
# String


# Character (In Python, a single character is just a string of length 1)


# --- Boolean ---
# Boolean values


# --- Arrays (Lists) ---
# List


# Accessing list elements


# Adding to a list


# --- Objects (using classes) ---



# Create an object of the Person class


# --- Type Conversion ---
# Convert integer to float


# Convert float to integer (truncates the decimal part)


# Convert boolean to integer


# --- Type Checking ---

"""# 1. Hello, World! (First Program)

This is a simple introduction to Python syntax and the print() function.
"""

# Basic "Hello, World!" example

"""# 2. Basic Math Operations

Introduce variables and arithmetic operators.
"""

# Simple math operations


# Addition

# Subtraction

# Multiplication

# Division

"""# 3. Getting User Input

Demonstrates how to interact with the user via input().
"""

# Getting user input and using it
name = input("what's your name? >>> ")
print("Hello " + name + "!")

# Working with numbers
age = input("How old you? >>> ") #strimg
print("Next year, you will be "  + str(int(age)+1)+"!")

"""# 4. If Statements (Conditionals)

Introduce the concept of decision-making using if, else, and elif.
"""

# Basic if-else example
number = int(input('Enter a number: >>> '))

if number > 0:
  print("You are positive!")
  if number % 2 == 0:
    print("You are even!")
  else:
      print("You are odd!")
else:
  print("You are negative!")

"""# 5. For Loop (Iteration)

A basic introduction to loops with a for loop that repeats a certain number of times.
"""

# Basic for loop example
for x in range(10,20):
  print("Loop iteratuon", x)

"""# 6. While Loop (Iteration with Condition)

Demonstrates a loop that runs until a condition is met.
"""

# Basic while loop example
# For loops need:
# 1. start point
# 2. end point (condition)
# 3. step


start = 1 #start point
while start <= 12: # end point (condition)
     print(count)

"""# 7. Basic Function Example

Introducing how to write and call functions.
"""

# Function to greet the user

"""# 8. Simple Temperature Converter

Combines input, conditionals, and functions in a real-world example.
"""

# Function to convert Celsius to Fahrenheit


# Get temperature from user

"""# 9. Simple Guessing Game

A fun exercise that involves loops, conditionals, and randomness.
"""

# Generate a random number between 1 and 10


# Keep asking the user until they guess correctly

"""# 10. FizzBuzz (Classic Example)

A popular coding challenge that helps beginners practice conditionals and loops.

**Problem Statement:**

Print numbers from 1 to n, where n is a positive integer. For each number:

- Print "Fizz" if the number is divisible by 3.
- Print "Buzz" if the number is divisible by 5.
- Print "FizzBuzz" if the number is divisible by both 3 and 5.
- Print the number itself if it is not divisible by either 3 or 5.
"""

# FizzBuzz example

"""# Bonus: Recursive Fibonacci Function

A more advanced example that demonstrates recursion.
"""

def fibonacci(n):
    # Base cases

        # Recursive case: F(n) = F(n-1) + F(n-2)


# Example usage

